### ISSUE TITLE
Suggestion: Game Over

### ISSUE THREAD

**Issue by lovac42** [Yutsuten/anki-life-drain#12]
How about throwing a signal once progress reaches zero. Something like:
`runHook("LifeDrain.GameOver")`
I'll have another script that catches these signals and do something.
- Display game over screen.
- Crash and restart Anki, loose all unsaved review progress.

**Comment by Yutsuten** [comment]
Oh, that's a nice idea!
Within the hook it is possible to do anything, so cool things can happen. Lets do it! 

This week I'll search how to do that and implement it.
Any update I'll leave a message here.

Thanks!

**Comment by lovac42** [comment]
Made some scripts for the new hook. Could use one for recovery and restart.
https://github.com/lovac42/LifeDrain_EndGames

**Comment by Yutsuten** [comment]
`recovery` and `restart` hooks are interesting, but for what you created only one is enough I think.

If I create the recovery one with no limit to the value, it will be possible to do something like `runHook('LifeDrain.recovery', 9999)`. It would restart the life.
Or the meaning of `restart` wasn't to recover all life?

---

By the way, to let things even more interesting, I'm thinking about `recovery` allowing any range of numbers (including negative ones), and a `setLife` to set the current life value.

**Comment by NicolasCuri** [comment]
This is such an awesome idea. Makes gamification a little more challenging. An idea would be to **create a "lockdown" for X minutes** in Anki, **reproduce an unpleasant sound** (a failure sound) and also **create a report on how many sessions have you failed** (and when) **when your life is over.** So every time you fail in a session, it penalizes you with a 5 minute (for example) lockdown in Anki, meaning that you cannot study until your penalty time is done. This approach would be good according to behavioral techniques of an operant conditioning and improve our efforts towards positive reinforcement and a reward (maybe introduce in the add-on the concept of the puppy reinforcement or any other kind of positive reinforcement for keeping up the pace) or running away from a negative reinforcement when you fail.

**Comment by Yutsuten** [comment]
Finished creating the hooks, the script can be found [here](https://github.com/Yutsuten/anki-life-drain/blob/game-over/lifedrain/lifedrain.py).

- It runs the `LifeDrain.gameOver` hook when life goes to 0.
- Allow running `LifeDrain.recover` hook from another add-ons.

`LifeDrain.recover` have 2 optional parameters: 1st is increment (boolean), True to recover and False to drain. 2nd is value (integer). If value is not provided, it is used the recover value set by the user (value found in deck preferences).

I'll wait a while until releasing it to check if the changes doesn't break anything.

**Comment by NicolasCuri** [comment]
One question: what if someone is using Life Drain as a Pomodoro timer (1500s max life, 0s recover) like myself? Will it have the same outcome as someone that uses the default settings (120s max 5s recover)?

**Comment by NicolasCuri** [comment]
Oh, ok! But I'm really interested in all this, this is very interesting and might improve my productivity. Looking forward to it.
