### ISSUE TITLE
Allow creating a session without Life Drain

### ISSUE THREAD

**Issue by NicolasCuri** [Yutsuten/anki-life-drain#14]
Just a small suggestion for the next update: being able to not use the life drain add-on without having to disable the add-on and restart Anki. I don't like to rush myself during reviews sometimes, so I'm constantly having to disable the add-on and restart Anki to create a session without Life Drain. It would be cool to have an easier way to review without using it and without having to toggle enable/disable the add-on every time. Also, I'd like to donate some money for this awesome work of yours (is there a link?). Thank you so much! :)

**Comment by Yutsuten** [comment]
Thank you for the feedback! I'm happy to know you're enjoying the addon that much!

The suggestion about creating a session without Life Drain is nice, I'll add it to the next update!
A checkbox in the Preferences may do the work.

About donating money, there's currently no way to do that.
My objective with this addon isn't to make money, so not sure about enabling a way to do that.
But thank you very much, anyway!

**Comment by Yutsuten** [comment]
I finished adding the option to disable the add-on, you may want to [try it out](https://github.com/Yutsuten/anki-life-drain/blob/disable/lifedrain/lifedrain.py) and check if it working without problems at your side.

You'll find the checkbox that disables the add-on in the Preferences.

**Comment by NicolasCuri** [comment]
Working 100% fine. Awesome!
