### ISSUE TITLE
autosync incoming deletion error

### ISSUE THREAD

**Issue by khonkhortisan** [Yutsuten/anki-life-drain#15]
```
La sincronización ha fallado:
Traceback (most recent call last):
  File "aqt\sync.py", line 382, in _sync
  File "aqt\sync.py", line 362, in _abortingSync
  File "anki\sync.py", line 90, in sync
  File "anki\sync.py", line 308, in remove
  File "<decorator-gen-124>", line 2, in remCards
  File "anki\hooks.py", line 66, in decorator_wrapper
  File "anki\hooks.py", line 58, in repl
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 802, in delete
    lifeDrain = getLifeDrain()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\715575551\lifedrain.py", line 94, in getLifeDrain
    'position': mw.col.conf.get('barPosition', DEFAULTS['barPosition']),
AttributeError: 'NoneType' object has no attribute 'conf'
```
I have it set to autosync on startup, and this error makes it fail the first sync, making me wait 5 minutes for it to forget about that attempt for a later manual sync to succeed.
Looks like life drain hooks into card deletion to adjust the bar size assuming the card was deleted while studying, but remotely deleting a card and syncing that deletion before the bar appears (or before the decks page appears?) makes it get ahead of itself.
The fix should end up being something simple like
`'position': mw.col and mw.col.conf.get('barPosition', DEFAULTS['barPosition']) or "top",`
Some info:
Anki 2.1.6-beta2
![image](https://user-images.githubusercontent.com/1996449/49655456-90677780-f9ef-11e8-90ea-a3bbe9d6d8eb.png)
![image](https://user-images.githubusercontent.com/1996449/49655528-b856db00-f9ef-11e8-974d-3c3eadb8d750.png)

**Comment by NicolasCuri** [comment]
I'm having the same error, with Anki 2.1.6beta2 as well.

Print attached:
![image](https://user-images.githubusercontent.com/39147974/49669998-e9f89200-fa41-11e8-8ea2-75366b7c484c.png)

**Comment by Yutsuten** [comment]
I don't use the autosync feature, so I've never seen this error, but by looking the traceback I understood what happened.

I've created a PR with a fix on it, tried enabling autosync on my machine and its all okay, could @khonkhortisan @NicolasCuri replace the script in your machines with the one [here](https://github.com/Yutsuten/anki-life-drain/blob/autosync-fix/lifedrain/lifedrain.py) and see if it solves your problem?

If it solves, I'd like to publish the fix to ankiweb as soon as possible, so please leave a message here with the result.

Thank you!

**Comment by lovac42** [comment]
nonetype errors are caused by replacing self.col with mw.col. When it syncs, it can't find mw.col when the collection is disconnection. I had my headaches with those. You have to sync multiple times just to make sure.

**Comment by Yutsuten** [comment]
`self.col` and `mw.col` points to the same place: The user's collection.

From the Anki documentation for [Writing Anki 2.1.X Addons](https://apps.ankiweb.net/docs/addons.html#the-collection):
_All operations on a collection file are accessed via mw.col. (...) You can’t run them directly in an add-on, as add-ons are initialized during Anki startup, before any collection or profile has been loaded._

The problem is that my script was trying to access the collection before it was loaded, thus the NoneType exception raised.
